### ISSUE TITLE
I tried to run it from src and it says missing ? Know what is the issue behind it.

### ISSUE THREAD

**Issue by mdabir1203** [Tauseef-Hilal/Pathfinding-Visualizer#1]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/66947064/217778543-c5a00609-ebe1-481d-8686-44b84f3dbe08.png">

OS: Mac 10.15.7

**Comment by Tauseef-Hilal** [comment]
Oops, my bad. Hadn't updated the README file.

Run this command from the project directory:
```
python3 run.pyw
```

BTW, the animations are much better now, you should try the new version
